### ISSUE TITLE
Question about IsaacGym

### ISSUE THREAD

**Issue by doyeon-danny** [j3soon/nvidia-isaac-summary#1]
Hi, thank you to share the summary of Isaac platforms.

I am trying to make a project which is simulation based on IsaacGym and IsaacSim.
I want to run environments by steps, and it calls isaacsim with sensore(ex lidars, Cameras)
Do you think it is possible?
As I search about it more and more, I find that I cannot use or call Lidars and IsaacSim in Isaacgym.

Thank you.

**Comment by j3soon** [comment]
For using cameras in (Omni)IsaacGym, see: https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/main/docs/examples/training_with_camera.md

I'm not sure if it's possible to use Lidars though...

**Comment by j3soon** [comment]
Consider using the latest Isaac Lab instead.

References:
* https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/direct/cartpole/cartpole_camera_env.py
* https://isaac-sim.github.io/IsaacLab/source/features/tiled_rendering.html
